# Generated by Django 5.1.1 on 2024-09-11 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateTimeField(verbose_name='Fecha de venta')),
                ('tpv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpv.tpv')),
            ],
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField(default=1)),
                ('precio_venta', models.IntegerField(default=100)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpv.productproduct')),
                ('sale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpv.sale')),
            ],
        ),
    ]
