# Generated by Django 5.1.4 on 2024-12-27 21:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpv', '0002_sale_saleline'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='productos',
            field=models.ManyToManyField(through='tpv.SaleLine', to='tpv.productproduct'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de venta'),
        ),
    ]
