# Generated by Django 5.1.4 on 2024-12-30 19:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpv', '0003_sale_productos_alter_sale_sale_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ('name',), 'verbose_name': 'Categoría'},
        ),
        migrations.AlterModelOptions(
            name='productproduct',
            options={'ordering': ('name',), 'verbose_name': 'Producto'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ('tpv_id', 'sale_date'), 'verbose_name': 'Venta'},
        ),
        migrations.AlterModelOptions(
            name='stockquant',
            options={'ordering': ('tpv_id', 'product_id'), 'verbose_name': 'Existencia'},
        ),
        migrations.AlterModelOptions(
            name='tpv',
            options={'ordering': ('name',), 'verbose_name': 'Punto de venta'},
        ),
        migrations.AlterField(
            model_name='productproduct',
            name='image',
            field=models.FileField(upload_to='media/uploads/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de compra')),
                ('tpv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpv.tpv')),
            ],
            options={
                'verbose_name': 'Compra',
                'ordering': ('tpv_id', 'purchase_date'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField(default=1)),
                ('precio_compra', models.IntegerField(default=100)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpv.productproduct')),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpv.purchase')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='productos',
            field=models.ManyToManyField(through='tpv.PurchaseLine', to='tpv.productproduct'),
        ),
    ]
