# Generated by Django 5.1.4 on 2025-01-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpv', '0004_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productproduct',
            name='precio_costo',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='productproduct',
            name='precio_venta',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='precio_compra',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='saleline',
            name='precio_venta',
            field=models.FloatField(default=100),
        ),
    ]
